name: CI Build, Lint, and Docker Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-rootkit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install build tools
        run: sudo apt update && sudo apt install -y build-essential
      - name: Build rootkit
        run: |
          cd rootkit
          make
      - name: Check rootkit.so exists
        run: test -f rootkit/rootkit.so

  lint-c-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install linters
        run: sudo apt update && sudo apt install -y clang-tidy cppcheck
      - name: Run clang-tidy
        run: clang-tidy rootkit/rootkit.c -- -I.
      - name: Run cppcheck
        run: cppcheck --enable=all --inconclusive --quiet rootkit

  docker-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t rootkit-lab .
      - name: Run rootkit inside Docker
        run: docker run --rm rootkit-lab

